//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.3

use sea_orm::entity::prelude::*;

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "role")]
pub enum Role {
    #[sea_orm(string_value = "Commenter")]
    Commenter,
    #[sea_orm(string_value = "Editor")]
    Editor,
    #[sea_orm(string_value = "Reader")]
    Reader,
}
